apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-test
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd-test
  project: default
  source:
    repoURL: 'https://github.com/cs0978/argo-cd-test.git'
    path: secret
