apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      init:
        command: [sh, -c]
        args: [echo, Initializing...]
      discover:
        find:
          command: [sh, -c]
          args: ["find . -name '*.yml' | xargs -I {} grep '<path' {} | grep ."]
      generate:
        command: [argocd-vault-plugin]
        args: [generate, .]
      lockRepo: false
